# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('created_at',)},
        ),
    ]
