# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20160908_0429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('created_at',), 'verbose_name': 'Life Goal'},
        ),
    ]
