# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20160908_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
